### ISSUE TITLE
Ambiguity error with `convert(NamedTuple, (;))`

### ISSUE THREAD

**Issue by mtfishman** [gcalderone/StructC14N.jl#2]
```julia
(@v1.7) pkg> st StructC14N
      Status `~/.julia/environments/v1.7/Project.toml`
  [d2514e9c] StructC14N v0.3.0

julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = vim

julia> convert(NamedTuple, (;))
NamedTuple()

julia> using StructC14N

julia> convert(NamedTuple, (;))
ERROR: MethodError: convert(::Type{NamedTuple}, ::NamedTuple{(), Tuple{}}) is ambiguous. Candidates:
  convert(::Type{T}, x::T) where T in Base at essentials.jl:218
  convert(::Type{NamedTuple}, str) in StructC14N at /home/mfishman/.julia/packages/StructC14N/7Prm0/src/StructC14N.jl:16
Possible fix, define
  convert(::Type{NamedTuple}, ::NamedTuple)
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```
We are hitting this in ITensors.jl (https://github.com/ITensor/ITensors.jl/issues/814) when we load `Gnuplot.jl`, which depends on `StructC14N.jl`.

**Comment by mtfishman** [comment]
This is some pretty bad type piracy:

https://github.com/gcalderone/StructC14N.jl/blob/8532216154c0e65a9966d7099badb0d65298ceb4/src/StructC14N.jl#L16-L19

Probably that should be a function with it's own name (such as an internal version of `convert`), it looks like that `convert` functionality is mostly meant to be used internally anyway.

**Comment by gcalderone** [comment]
The `convert(::Type{NamedTuple}, str)` method is not defined in `Base` when `str` is a structure.  But you're right, it's type piracy and I'm working to fix it first, then I'll look into the issue...

**Comment by mtfishman** [comment]
Thanks!

**Comment by gcalderone** [comment]
I'm registering the new version, it should be available in a few minutes...

**Comment by gcalderone** [comment]
Done, v0.3.1 is registered and available

**Comment by mtfishman** [comment]
Thanks for your help @gcalderone, nice that people will now be able to use ITensors.jl and Gnuplot.jl together!
